### ISSUE TITLE
Translation progress chart has not been updated since December 14th

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla-l10n/langchecker#424]
On Webdashbord, the progress chart is broken since Dec 14th, I suspect something broke in langchecker that day.

**Comment by flodolo** [comment]
The system is managed directly by @pascalchevrel it doesn't have any relation with langchecker ;-)
https://github.com/pascalchevrel/web_l10n_stats

I know we talked about it in the past, and how it should use directly langchecker's data instead of calculating its own stats, but I don't think he rewrote it yet.

**Comment by TheoChevalier** [comment]
I thin  I’ve found the error, on December 14th we added new dependencies: https://github.com/mozilla-l10n/langchecker/commit/ac95211dac4b0624978664c268966357bc9fbc42#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R24

Except that… we’re missing the update command while trying to update composer :) https://github.com/pascalchevrel/web_l10n_stats/blob/master/dig.php#L190

Fixed here https://github.com/pascalchevrel/web_l10n_stats/pull/3 and I will rewrite it to use production Langchecker

**Comment by flodolo** [comment]
Fixed by https://github.com/mozilla-l10n/web_l10n_stats/pull/3
